# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4beabf3dee10c096f3a55185cc3f3332c1aaf8c2b97dd41e68397c2b6fb0e7f6bf873d762cfe8edb4fc61bfeee13b492d684dc5c1fec6a2790b863208b79ff9f

test:
  secret_key_base: ff346e899c95164b652d08b2fa84d4b5a8d03119639ec2d25b144bf9c6d3d1c8e34527089eeb1ea4e367e81b860dad237549b5ac6a61198637b02b322f446529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
